"""Constants for the Electrolux integration."""

DOMAIN = "electrolux"

APPCODE_ELECTROLUX = "electrolux"
HOST_RUSKLIMAT = "http://dongle.rusklimat.ru"
LANG = "ru"

DEFAULT_NAME = "Electrolux Convector"
DEFAULT_MIN_TEMP = 11
DEFAULT_MAX_TEMP = 35

PLATFORMS = ["climate"]

###
# CONVECTOR CONST
###
STATE_OFF = 0
STATE_ON = 1

MODE_COMFORT = 0
MODE_ECO = 1
MODE_NO_FROST = 2
MODE_OFF = 3

PRESET_0 = 0
PRESET_1 = 1
PRESET_2 = 2
PRESET_3 = 3
PRESET_4 = 4
PRESET_5 = 5
PRESET_6 = 6
PRESET_7 = 7

BRIGHTNESS_MODE_HALF = 0
BRIGHTNESS_MODE_FULL = 1

TEMP_COMFORT_MIN = 10
TEMP_COMFORT_MAX = 35

DELTA_ECO_DEFAULT = 4
TEMP_ANTIFROST_DEFAULT = 3

HEAT_MODE_AUTO = 0
HEAT_MODE_MANUAL = 1

LED_MODE_PERMANENT = 0
LED_MODE_AUTO = 1

POWER_0 = 0
POWER_1 = 1
POWER_2 = 2
POWER_3 = 3
POWER_4 = 4
POWER_5 = 5

TYPE_CONVECTOR_2 = "convector24"

